# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_Item_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 181)
        self.title = QtWidgets.QLineEdit(Form)
        self.title.setGeometry(QtCore.QRect(120, 20, 201, 20))
        self.title.setText("")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label.setObjectName("label")
        self.date = QtWidgets.QDateEdit(Form)
        self.date.setGeometry(QtCore.QRect(120, 50, 111, 22))
        self.date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date.setObjectName("date")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.btnImage = QtWidgets.QPushButton(Form)
        self.btnImage.setGeometry(QtCore.QRect(120, 80, 111, 23))
        self.btnImage.setObjectName("btnImage")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 311, 16))
        self.label_4.setObjectName("label_4")
        self.btnAdd = QtWidgets.QPushButton(Form)
        self.btnAdd.setGeometry(QtCore.QRect(20, 140, 301, 23))
        self.btnAdd.setObjectName("btnAdd")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новый продукт"))
        self.label.setText(_translate("Form", "Название:"))
        self.date.setDisplayFormat(_translate("Form", "dd.MM.yyyy"))
        self.label_2.setText(_translate("Form", "Срок годности:"))
        self.btnImage.setText(_translate("Form", "Выбрать*"))
        self.label_3.setText(_translate("Form", "Изображение:"))
        self.label_4.setText(_translate("Form", "*При отсутствии изображения присваивается стандартное"))
        self.btnAdd.setText(_translate("Form", "Добавить"))
