# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 160)
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.btn1.setStyleSheet("background-color: rgb(152, 251, 152);")
        self.btn1.setText("")
        self.btn1.setObjectName("btn1")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn1)
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(110, 20, 81, 81))
        self.btn2.setStyleSheet("background-color: rgb(255, 250, 205);")
        self.btn2.setText("")
        self.btn2.setObjectName("btn2")
        self.buttonGroup.addButton(self.btn2)
        self.btn3 = QtWidgets.QPushButton(Form)
        self.btn3.setGeometry(QtCore.QRect(200, 20, 81, 81))
        self.btn3.setStyleSheet("background-color: rgb(240, 128, 128);")
        self.btn3.setText("")
        self.btn3.setObjectName("btn3")
        self.buttonGroup.addButton(self.btn3)
        self.btnDefault = QtWidgets.QPushButton(Form)
        self.btnDefault.setGeometry(QtCore.QRect(20, 120, 261, 23))
        self.btnDefault.setObjectName("btnDefault")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.btnDefault.setText(_translate("Form", "Сбросить цвета"))
